services:
 
  # DB (PostgreSQL)
  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: myapp_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d/init
      - ./database/migrations:/docker-entrypoint-initdb.d/migrations
      - ./database/seeds:/docker-entrypoint-initdb.d/seeds
    restart: unless-stopped

  # PHP BACKEND
  php:
    build:
      context: .
      dockerfile: .docker/Dockerfile.php
      args:
        PHP_VERSION: ${PHP_VERSION}                            # Передаем переменную из .env в Dockerfile
    container_name: myapp_php
    volumes:
      - ./backend:/app
    working_dir: /app/public
    command: php -S 0.0.0.0:${PHP_PORT}
    ports:
      - "${PHP_PORT}:${PHP_PORT}"
    restart: unless-stopped

# Хранилище для данных БД (чтобы не терялись при перезапуске)
volumes:
  db_data:

# Сеть для связи контейнеров
networks:
  app_network:
    driver: bridge