services:
  php:
    build:
      context: .
      dockerfile: .docker/Dockerfile.php
      args:
        # Передаем переменную из .env в Dockerfile
        PHP_VERSION: ${PHP_VERSION}
    container_name: myapp_php
    volumes:
      - ./backend:/app
    working_dir: /app/public
    command: php -S 0.0.0.0:${PHP_PORT}
    ports:
      - "${PHP_PORT}:${PHP_PORT}"
    restart: unless-stopped